# Generated by Django 4.2.8 on 2024-02-03 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(max_length=255)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('unit_number', models.IntegerField(blank=True, null=True)),
                ('plate_number', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=20, unique=True)),
                ('coordinate', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('floors', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('major', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('office_hours', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('is_committee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home')], default='Mobile', max_length=6)),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Instructor', 'Instructor'), ('Assistant Professor', 'Assistant Professor'), ('Associative Professor', 'Associative Professor'), ('Full Professor', 'Full Professor')], max_length=255)),
                ('is_in_committee', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('search_area', models.TextField()),
                ('funding_source', models.TextField()),
                ('budget', models.IntegerField()),
                ('description', models.TextField()),
                ('publication', models.TextField()),
                ('keywords', models.TextField()),
                ('status', models.CharField(choices=[('ToDo', 'ToDo'), ('InProgress', 'InProgress'), ('Done', 'Done')], default='ToDo', max_length=10)),
                ('website', models.TextField(blank=True, null=True)),
                ('related_research', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sat', 'Saturday'), ('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.professor')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.research')),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_first_name', models.CharField(max_length=255)),
                ('persian_last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=20, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('educations', models.ManyToManyField(to='api.education')),
                ('home_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address')),
                ('phone_numbers', models.ManyToManyField(to='api.phonenumber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('books', models.IntegerField()),
                ('managers', models.ManyToManyField(to='api.employee')),
                ('schedules', models.ManyToManyField(to='api.schedule')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipments', models.TextField()),
                ('capacity', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('managers', models.ManyToManyField(to='api.employee')),
                ('schedules', models.ManyToManyField(to='api.schedule')),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_field', to='api.professor'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ManyToManyField(to='api.office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
        migrations.CreateModel(
            name='DepartmentResponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professor')),
                ('education_deputy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_deputy', to='api.professor')),
                ('education_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_officer', to='api.employee')),
                ('financial_deputy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_deputy', to='api.employee')),
                ('graduated_education_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_education_officer', to='api.employee')),
                ('office_adminstrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_adminstrator', to='api.employee')),
                ('research_deputy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_deputy', to='api.professor')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
        ),
    ]
