# Generated by Django 4.2.8 on 2024-02-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_building_name_alter_address_coordinate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Phone Number', 'verbose_name_plural': 'Phone Numbers'},
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
