# Generated by Django 4.2.8 on 2024-02-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_phonenumber_options_alter_person_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Office', 'verbose_name_plural': 'Offices'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterField(
            model_name='field',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_field', to='api.professor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='educations',
            field=models.ManyToManyField(to='api.education'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_numbers',
            field=models.ManyToManyField(to='api.phonenumber'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='research',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='related_research',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchmember',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
        migrations.AlterField(
            model_name='researchmember',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.researcher'),
        ),
    ]
