# Generated by Django 5.0.1 on 2024-01-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_emailchangepassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailchangepassword',
            options={'verbose_name': 'Email Change Password', 'verbose_name_plural': 'Emails Change Password'},
        ),
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'New User', 'verbose_name_plural': 'New Users'},
        ),
    ]
