# Generated by Django 5.0.1 on 2024-02-01 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_city_country_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default='Tehran', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default='Iran', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.country', verbose_name='Country'),
        ),
    ]
