# Generated by Django 5.0.1 on 2024-01-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='blogdescription',
            options={'verbose_name': 'Description', 'verbose_name_plural': 'Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='blogdescriptionitem',
            options={'verbose_name': 'Description Item', 'verbose_name_plural': 'Description Items'},
        ),
        migrations.AlterModelOptions(
            name='bloglabel',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterModelOptions(
            name='likesblogcomment',
            options={'verbose_name': 'Comment Like', 'verbose_name_plural': 'Comment Likes'},
        ),
    ]
