FROM node:lts-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /code/

COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install

ENV PATH /code/node_modules/.bin:$PATH

