# Generated by Django 5.0.1 on 2024-01-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Awaiting Payment', 'Awaiting Payment'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50, verbose_name='Status')),
                ('method', models.CharField(choices=[('Online', 'Online'), ('Card by card', 'Card by card')], default='Online', max_length=50, verbose_name='Method')),
                ('payment_date', models.DateTimeField(verbose_name='Payment Date')),
                ('tax_amount', models.PositiveIntegerField(verbose_name='Tax Amount')),
                ('transaction_image', models.FileField(upload_to='document/transaction/income_teacher', verbose_name='Transaction Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ManyToManyField(related_name='teacher_income', to='course.course', verbose_name='Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='teacher.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Income',
                'verbose_name_plural': 'Teacher Incomes',
            },
        ),
    ]
