# Generated by Django 5.0.1 on 2024-01-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherincome',
            options={'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
    ]
