# Generated by Django 5.0.1 on 2024-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('customer', '0002_customer_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, related_name='course', to='customer.customer', verbose_name='Costumer'),
        ),
    ]
