# Generated by Django 5.0.1 on 2024-01-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_customer'),
        ('customer', '0002_customer_is_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursecertificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='coursedescription',
            options={'verbose_name': 'Description', 'verbose_name_plural': 'Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='coursedescriptionitem',
            options={'verbose_name': 'Description Item', 'verbose_name_plural': 'Description Items'},
        ),
        migrations.AlterModelOptions(
            name='courselabel',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterModelOptions(
            name='courselikes',
            options={'verbose_name': 'like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterField(
            model_name='course',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='course', to='customer.customer', verbose_name='Costumer'),
        ),
    ]
