# Generated by Django 5.0.1 on 2024-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Face to face class', 'IN PERSON'), ('Online class', 'ONLINE'), ('Online and Face-to-face classes', 'IN PERSON AND ONLINE')], default='Online class', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_time',
            field=models.DurationField(default=0, verbose_name='Video Time'),
        ),
    ]
