# Generated by Django 5.0.1 on 2024-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Is valid'),
        ),
    ]
