# Generated by Django 5.0.1 on 2024-02-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0002_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="person_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="laboratory.person",
                unique=True,
            ),
        ),
    ]
