# Generated by Django 5.0.1 on 2024-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0003_alter_student_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=100
            ),
        ),
    ]
