# Generated by Django 5.0.1 on 2024-02-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0004_alter_person_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="work_time",
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="person_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="laboratory.person",
                unique=True,
            ),
        ),
    ]
