# Generated by Django 5.0.1 on 2024-01-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_teaching_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveleducation',
            name='name_university',
            field=models.CharField(max_length=50, verbose_name='Name University'),
        ),
    ]
