# Generated by Django 5.0.1 on 2024-01-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_leveleducation_name_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='learningـpercentage',
            field=models.FloatField(default=0, verbose_name='Learning percentage'),
        ),
    ]
