# Generated by Django 5.0.1 on 2024-01-17 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(max_length=50, verbose_name='Total price')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Is Discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.PositiveIntegerField(verbose_name='FINAL PRICE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATED AT')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='course.course', verbose_name='COURSE')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order', verbose_name='ORDER')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
