# Generated by Django 5.0.1 on 2024-01-18 15:16

import apps.account.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('currency', models.CharField(choices=[('Rial', 'Rial'), ('Dollar', 'Dollar')], default='Rial', max_length=50, verbose_name='Currency')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('Paid', 'PAID'), ('Unpaid', 'UNPAID'), ('Awaiting Payment', 'AWAITING PAYMENT')], default='Unpaid', max_length=50, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sender_card_number', models.CharField(max_length=11, validators=[apps.account.validators.validate_credit_card_number], verbose_name="Sender's Card Number")),
                ('recipient_card_number', models.CharField(max_length=11, validators=[apps.account.validators.validate_credit_card_number], verbose_name="Recipient's Card Number")),
                ('transaction_image', models.FileField(upload_to='document/transaction/user', verbose_name='Transaction Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ManyToManyField(related_name='transaction', to='course.course', verbose_name='Course')),
                ('teacher', models.ManyToManyField(related_name='transaction', to='teacher.teacher', verbose_name='Teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
